theme = "tangram"

[editor]
bufferline = "always"
clipboard-provider = "pasteboard"
color-modes = true
cursorline = true
end-of-line-diagnostics = "warning"
shell = ["nu", "--stdin", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
character = "│"
render = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true

[editor.smart-tab]
supersede-menu = true

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["file-name", "file-modification-indicator"]
left = ["mode", "position", "total-line-numbers"]
right = ["diagnostics", "workspace-diagnostics", "spinner"]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = " "

[keys.normal]
"A-down" = "select_line_below"
"A-up" = "select_line_above"
"C-A-s" = ":wa"
"C-A-w" = ":bca"
"C-h" = "goto_previous_buffer"
"C-j" = "goto_next_paragraph"
"C-k" = "goto_prev_paragraph"
"C-l" = "goto_next_buffer"
"C-n" = ":new"
"C-q" = ":q"
"C-r" = ":reload"
"C-s" = ":w"
"C-w" = ":bc"
"C-y" = ':sh echo "%{buffer_name}:%{selection_line_start}-%{selection_line_end}" | pbcopy'
"left" = "jump_backward"
"right" = "jump_forward"
G = "goto_last_line"
H = "select_prev_sibling"
J = "shrink_selection"
K = "expand_selection"
L = "select_next_sibling"
g = { e = "goto_file_end" }

[keys.normal."up"]
D = "goto_first_diag"
G = "goto_first_change"
T = "goto_prev_test"
a = "goto_prev_parameter"
c = "goto_prev_comment"
d = "goto_prev_diag"
f = "goto_prev_function"
g = "goto_prev_change"
p = "goto_prev_paragraph"
t = "goto_prev_class"

[keys.normal."down"]
D = "goto_last_diag"
G = "goto_last_change"
T = "goto_next_test"
a = "goto_next_parameter"
c = "goto_next_comment"
d = "goto_next_diag"
f = "goto_next_function"
g = "goto_next_change"
p = "goto_next_paragraph"
t = "goto_next_class"

[keys.select]
"A-down" = "select_line_below"
"A-up" = "select_line_above"
"C-A-s" = ":wa"
"C-A-w" = ":bca"
"C-h" = "goto_previous_buffer"
"C-j" = "goto_next_paragraph"
"C-k" = "goto_prev_paragraph"
"C-l" = "goto_next_buffer"
"C-n" = ":new"
"C-q" = ":q"
"C-r" = ":reload"
"C-s" = ":w"
"C-w" = ":bc"
"C-y" = ':sh echo "%{buffer_name}:%{selection_line_start}-%{selection_line_end}" | pbcopy'
"left" = "jump_backward"
"right" = "jump_forward"
G = "goto_last_line"
H = "select_prev_sibling"
J = "shrink_selection"
K = "expand_selection"
L = "select_next_sibling"
g = { e = "goto_file_end" }

[keys.select."up"]
D = "goto_first_diag"
G = "goto_first_change"
T = "goto_prev_test"
a = "goto_prev_parameter"
c = "goto_prev_comment"
d = "goto_prev_diag"
f = "goto_prev_function"
g = "goto_prev_change"
p = "goto_prev_paragraph"
t = "goto_prev_class"

[keys.select."down"]
D = "goto_last_diag"
G = "goto_last_change"
T = "goto_next_test"
a = "goto_next_parameter"
c = "goto_next_comment"
d = "goto_next_diag"
f = "goto_next_function"
g = "goto_next_change"
p = "goto_next_paragraph"
t = "goto_next_class"
